apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "wine-model-workshop"
  namespace: kserve-inference
  # annotations:
  #   prometheus/io/scrape: "true"
spec:
  predictor:
    serviceAccountName: kserve-sa # created when deploying the MLOps platform, associating with the secret that contains the username and password of the MLflow's MinIO server
    model:
      modelFormat: 
        name: sklearn
      storageUri: "s3://mlflow/8/e1181c1b1bcd442fba6e8a0d700427d5/artifacts/model" # replace
      # minio at localhost:9001 has paths like: mlflow/1/1d549a9d646e4e11968493208b8a868d/artifacts/model replace it to the above
      # make sure to include the s3:// in front